### PR TITLE
Run Faster "Buying the Basics"

### PR DESCRIPTION
**Pull request by HaikenEdge**
Implemented data entry for all items except "Piece of Betel Gum" in the "Buying the Basics" section (pg 253-255) of *Run Faster* (pg 253-255). Excluded "Piece of Betel Gum" entry because the price conflicts with "Betel", which is the same item and was printed in *Chrome Flesh* with a listed price of 5¥, conflicting (and superceding, due to being a newer book) the *Run Faster* listed price of 1¥.

### CODE REVIEW

**Comment by cfresquet** [comment]
I thought Betel gum was 5¥ for a pack, 1¥ for a single stick?
...with no specification of how many sticks in a pack.

**Comment by HaikenEdge** [comment]
Betal is listed as 5¥ per dose in *Chrome Flesh*, which I would think would be a single piece, and not an entire pack.

**Comment by cfresquet** [comment]
Hmn.  You are correct, sir.  Plus it is listed as 5¥ in two different places in Chrome Flesh, while the entry in Run Faster is more of a background/flavor reference.

I'd say 5¥ should pretty clearly be the correct price.

**Comment by HaikenEdge** [comment]
Hence the reasoning as to why the entry was excluded.

**Pull request merged**
