### PR TITLE
Made some Translations, corrected some grammar mistakes, corrected some formatting problems

### PR DESCRIPTION
**Pull request by HaukeW**
Formatting: Some lines were not formatted like the others (Spaces instead of tabs) Changed that to make all lines conform in syntax.

### CODE REVIEW

**Comment by joha4270** [comment]
So i'm fine merging this now if you want, but if you look at the books section under options quite a few of them aren't translated. 
I'm not familiar with the translator or exactly how you do the data entry, but for an example, it can see it tries to match "Run Faster German" while the English title actually is "Run Faster (German)"
They probably needs to match **_exactly_**

**Comment by HaukeW** [comment]
Hm, I see.
My Problem is that I don´t know exactly, what the values mean. The books are handled - as far as I see it - in de_data.xml -> books.xml.
But: There are These values:

```
<book>
	<id>f5ec713c-98cd-41f6-a0a4-4a8eaed55b66</id>
	<name>Shadowrun 5th Edition</name>
	<translate>Shadowrun 5. Edition</translate>
</book>
[...]
<book>
	<id>b3c5ea18-56dc-42f4-b567-50ead12fab1f</id>
	<name>Shadowrun 5th Edition (German)</name>
	<translate>Shadowrun 5. Edition (Deutsch)</translate>
</book>
[...]
<book>
	<id>be0638b9-f005-42e3-83e1-97d806f5b070</id>
	<name>Run Faster German</name>
	<translate>Schattenläufer</translate>
</book>

```
The firt value is for the english version of the core rulebook, the second one is for the german one. "Run Faster" is named "Schattenläufer" in german. But - other than for the core rulebook where "<name>Shadowrun 5th Edition</name>" supposedly means the english Version of the book - there is no such double value for "Run Faster".

So should i Change this to:

```
<book>
	<id>be0638b9-f005-42e3-83e1-97d806f5b070</id>
	<name>Run Faster</name>
	<translate>Schattenläufer</translate>
</book>
```
?
I really don´t know...

**Comment by joha4270** [comment]
I would change it to "Shattenläufer deutche inhalt" or something like that (might be showing my german lessons didn't make a huge impact)

**Comment by joha4270** [comment]
I'm seeing strassgriminore (deutch) now, so some of it works.
Your call if you want me to merge this chunk or wait for it all.

Regarding missing entries in de_data, i'm going to investigate in the soonish. I have your email, so once i have found out how it works, i'll send you instructions there. Ill try to make it work using the translator, but it might require to you get your hands dirty in a text editor

**Comment by HaukeW** [comment]
Should I name all books that have a translation with "x (German)"

At the Moment it is for almost all books (except for the core rulebook and now Street Grimoire) like this one:

```
<book>
	<id>ab9fd70c-6b79-4780-ae3d-dfa5f1624c9d</id>
	<name>Stolen Souls</name>
	<translate>Gestohlene Seelen</translate>
</book>
```

Should this be changed everywhere to:

```
<book>
	<id>ab9fd70c-6b79-4780-ae3d-dfa5f1624c9d</id>
	<name>Stolen Souls (German)</name>
	<translate>Gestohlene Seelen</translate>
</book>
```

**Comment by chummer5a** [comment]
Nah, that's for the versions that have different content.

**Comment by HaukeW** [comment]
ok. Then you can merge now. I guess I can´t do more then at the Moment.

P.S: What do you mean with "different content"? Isn´t the Point of translated books to have different Content (regarding language, page numbers, errata...)

**Comment by OLStefan** [comment]
I think he meant stuff like the additional mentor spirits from "Straßengrimoire"

**Comment by chummer5a** [comment]
Take the Raven mentor spirit, for example. The German book has different content to the standard one, so we differentiate it by adding a new book.

**Pull request merged**
