### PR TITLE
Shapeshifter pull request

### PR DESCRIPTION
**Pull request by SRgithub5**

### CODE REVIEW

**Comment by DelnarErsike** [comment]
You didn't modify the Visual Studio project to include the new files during compilation. Do you want to do that yourself (so that you know how to do it in the future) or for me to do it for you after the merge?

**Comment by SRgithub5** [comment]
> 

I'm not sure what the Visual Studio project is, I would love to know how to update things correctly. At one point while testing I noticed that in a menu, some things didn't seem alphabetical, so maybe that was my sign that I'd missed something that needed to be updated.

**Comment by DelnarErsike** [comment]
Visual Studio is a (hefty and cumbersome) IDE (Integrated Developer Environment) released and maintained by Microsoft. You can download Community Editions for free, and that will be sufficient for this. Once you have your preferred version downloaded (2022 or 2019 will both do), open up `Chummer.sln` with it. This opens up the Chummer5a solution file that contains the 10 or so projects that Chummer uses. The one you'll be interested in would be the Chummer5a project.

Inside Visual Studio's solution explorer sidebar, navigate to where the newly added files would be in the `customdata` directory and add your newly added folder and files to the project. You can do this by right-clicking in the appropriate location, clicking "Add a Folder", typing in the name you want, and then successively right clicking and selecting "Add Existing Item" and selecting the files to be in that folder. Alternatively, there's a button you can click somewhere in the corner of the Solution Explorer interface to show files not included in the project. Once you do that, you'll see the folder and the files for this pull request in the solution explorer, albeit grayed out. You can then right click them and add them to the project directly without needing to fiddle around with browsing for them.

**Comment by DelnarErsike** [comment]
This branch has been open for almost half a year now. If you do not want me to make the necessary edits for you, please make those edits before the sixth month mark. Otherwise, I will just merge this PR and make the edits myself.

**Pull request merged**
