### PR TITLE
NLog Implementation

### PR DESCRIPTION
**Pull request by ArchonMegalon**
Hi @chummer5a !

I have implemented NLog. This is a big change, although it's a pure replacement right now with no additional benefit right of the box (apart from everything the NLog library provides).

Please take a look at it if it still works (it does for me). The NLog.dll itself throws some FirstChanceExceptions in each Log-Call, that's why it's not possible any more to "Log" FirstChanceExceptions like we did previously in the Program startup. 

The Windows Eventlog can only be written to, if Chummer is started once as Admin because NLog needs to register an Eventsource to do that (just in case you take a look at the nlog.config file and wonder, why you can't find entries in your event log).

I replaced all the old "Log.Exception" calls with - what I think - a better "Log.Error(Exception)" or in some cases Log.Trace(Exception), when the exception acutally doesn't matter.

If you like this framework I would implement a new Option like "provide my Logs to the Devs online" and implement a Application Insights target for NLog.

### CODE REVIEW

**Comment by chummer5a** [comment]
I'd prefer not to use event log if admin rights are required. I'll have a poke at it later. Happy to expand the logging options, might be worth having it intercept the crash handler as well but I can look into that myself if it's a bit spooky.

**Comment by ArchonMegalon** [comment]
Ok, maybe that was misleading. Admin rights are NOT required at all for Logging to all kinds of targets (like into a file, a database, a webservice, a mailreceiver)

Only if you want to use the EventLog, they are required ONCE, because the Windows-OS prevents none-admins from ... well logging to the EventLog. 

It is perfectly usable even IF the Eventlog-Target is defined and it doesn't have the privileges. It just won't log there (because it's forbidden by the OS to do so).

**Comment by ArchonMegalon** [comment]
Actually - this is not ready yet. Wait a bit... Still fiddling around with application insights...

**Comment by ArchonMegalon** [comment]
Ok, works again! @chummer5a - give it a try. If you tell me your microsoft account I can share the azure-portal for the logging with you.

**Comment by chummer5a** [comment]
Looks fine to me at first blush, couple of things; 

- There's inconsistent use of the logger class being static in forms and equipment classes. Likely minor, but might be relevant for performance?  
- Is it possible to have the applicationinsights export to a file that users can send to us, or is it purely an API push? Super unimportant, but might help us to control the use of it.

Other than that, looks good!

**Comment by ArchonMegalon** [comment]
Well, i also wondered about the sometimes static and sometimes non static use. The unofficial answer I got was, that the GetCurrentClass Function should return a static anyway and it doesn't matter currently.
So we could make it static as well.  There was a BUT afterwards: There may be some changes in the future, that would make use of none-static logger instances, and if we force it to be static, we would not be able to use such features. He was talking about callbacks or such things I think, that are able to register on the logger. 

As far as I know it's not possible to have application insights generate a file. The API for example supports a live stream as well, that would not work that way. Of coures we are logging the same calls as NLog does, so if the user doesnt enable A(pplication) I(nsights), but only "Logging", he can just send us the file as well. AI is really just more comfortable for the end user.

Have you registered a microsoft account already to get access to the AI-Logs?

**Comment by chummer5a** [comment]
Toss it to chummer5isalive@gmail.com

**Comment by ArchonMegalon** [comment]
Can't, you can register here: https://account.microsoft.com

Doku:
To provide access to another user

You must have Owner rights to the subscription or the resource group.

The user must have a **Microsoft Account**, or access to their organizational Microsoft Account. You can provide access to individuals, and also to user groups defined in Azure Active Directory.

**Pull request merged**
