### PR TITLE
Fr translations

### PR DESCRIPTION
**Pull request by gdelmee**
Moving forward in fr-fr check

### CODE REVIEW

**Comment by chummer5a** [comment]
Sulking about conflicting file, prboably just needs to be squashed

**Comment by gdelmee** [comment]
I've moved lots of strings and done corrections. I understand the system has issues to auto merge.
I'm far from the end of the file, currently at line 2047.
If you prefer, I can continue and we can wait untill the file is completely done.

**Comment by ArchonMegalon** [comment]
That's weird. The conflicts seem to not actually be conflicts, since the master just seems to have more lines. Did you REMOVE lines? Why so? Or am I reading that merge wrong?

**Comment by gdelmee** [comment]
There was 9778 lines and I pushed a file of 9780 lines as I replicated regions, and so added to add end region lines.
Also, there are a lot of changed lines as Visual Studio corrected tabs (with tabify) even there was no changes.

**Comment by gdelmee** [comment]
I've double checked and I did made a mistake. I'll correct it for a further pull request.

**Pull request closed without merging**
