### PR TITLE
[WIP] Added Social Apperance Anxiety ratings 2 and 3

### PR DESCRIPTION
**Pull request by mudge6**
- [x] Added ranks
- [x] Added GUIDs

Im not sure how to add GUIDs, if someone more experienced could help, that would be nice.

### CODE REVIEW

**Comment by chummer5a** [comment]
Use something like https://www.guidgenerator.com. Most IDEs have something to generate them as well. I generally use the guid generator in http://phdesign.com.au/npptoolbucket with my notepad++ installation.

**Comment by mudge6** [comment]
@chummer5a alright just added GUIDs, anything need to be changed or added?

**Comment by chummer5a** [comment]
Hrm. You can probably implement the penalty with the skillcategory improvement type, see if this works
`        <skillcategory>
          <name>Social Active</name>
          <bonus>-1</bonus>
        </skillcategory>`

**Comment by mudge6** [comment]
@chummer5a personally i think that should be left out since its not active all of the time, unless you know of a way to have a modified dice pool added to the number

**Comment by chummer5a** [comment]
Oh right, it's conditional on not being pretty. Yeah, that's fine as is then.

**Pull request merged**
