### PR TITLE
Added Body Sculpt power data

### PR DESCRIPTION
**Pull request by HaikenEdge**

### CODE REVIEW

**Comment by joha4270** [comment]
Why is this 2 pulls?

**Comment by HaikenEdge** [comment]
Did I pull it twice? I thought I pulled the powers XML once and the book XML once.

**Comment by joha4270** [comment]
Exactly that.

There are no reason to have the power without the book or the book without
the power, so i don't see any reason to split it in multiple.

(but no worries, 1 or 2 buttons don't do a lot of difference, just
commenting)

**Comment by HaikenEdge** [comment]
Didn't realize you could put two edits into one pull request. My bad. I just put in a request based on the structure of GitHub, where had it listed pretty separately.

**Comment by joha4270** [comment]
As far as i can see, you did it in separate branches

Make all changes on one branch, then create a pull for that branch.

**Comment by HaikenEdge** [comment]
I'm not even sure how to do that. I just forked the files, edited them, and they ended up in different branches.

**Comment by joha4270** [comment]
You can fork files? I was under the impression you always forked an entire
repository.

Not that this is really important... so lets drop it and i'll get it merged

**Pull request merged**
