### PR TITLE
Vehicle/Drone modification tracking

### PR DESCRIPTION
**Pull request by skarsol**
So this adds display of the available modification slots for Vehicles and Drones. Vehicles show the 6 categories of mod pools and tracks them separately. Drones just show their single pool of mod slots. The free upgrade for each stat for Drones is accounted for. Immobile adds the 2 slots correctly, but I've not coded for the 1 mod point available by reducing a Drone stat by one. I'm thinking the best way for that would be to add a Negative Vehicle Mod which reduces the stat and adds the 1 mod point. Didn't want to do that till I got some comment on this patch and that concept.

This also fixes some code that I ran into in the process which still does things by old rules (Speed/Accel having percentage mods, etc). I couldn't find any instances where those still applied, but it was breaking current functionality.

This patch also fixes issue #780 and opens the path to fixing #787 with a gear similar to the modified Immobile.

### CODE REVIEW

**Comment by skarsol** [comment]
FYI, the drone code on this is notably lacking a switch to turn it off based on the Rigger 5.0 flag. I wasn't sure if it was best to use that flag or to create a new one (so you could use the other rules in Rigger 5, just not the drone mods rules (ie: you still want your assault rifles from SR5 :P))

**Comment by chummer5a** [comment]
Given that they do present multiple options for how to handle modifying your drones in the rulebook, I'd be happiest if it were an optional rule. I've had more than a few requests that it not be something we shove down people's throats. Shouldn't be a huge deal to implement, the Options code is pretty basic and there's already the rather basic IsDrone boolean if you want to go that far. Simplest way for us to handle the mod point increases is probably going to be mod items that have a negative bonus for whatever rating they are and a negative value for their Slots equal to rating.

**Comment by skarsol** [comment]
Well, this works on my test build. I'm not sure why Appveyor is failing. Looking at that commit, I don't see a merge issue. Not really sure how to investigate that.

**Comment by skarsol** [comment]
Found a couple things, set up the upstream link, got all up to date, Appveyor still complaining. Advice appreciated. :)

**Comment by chummer5a** [comment]
Appveyor tends to scream if it has to merge changes. Since I was doing stuff upstream with the Acceleration bug (Costs are listed as Acceleration * whatever instead of Accel), it got a bit unhappy. In theory should be fine now.

**Pull request merged**
