### PR TITLE
My first simply try of a commit./push. 

### PR DESCRIPTION
**Pull request by ArchonMegalon**
After deleting the Exeptional Attribute quality it happend to me to get an ArgumentOutOfRange here.

### CODE REVIEW

**Comment by ArchonMegalon** [comment]
Please just ignore this - I'm just trying to figure out how GitHub handles things...

**Comment by ArchonMegalon** [comment]
Ok, I'm just curious. I think I did that wrong. Did I request a merge for my old request and just added the fix for the spell drain here? How do I request a merge for another file regardless of the status of this "My first simple.." request. 

If I cant, can you just reject it, so that I can contribute again please?

**Comment by chummer5a** [comment]
You'd need to make a separate branch with your other change; GitHub merges them all into a single pull request if they're coming from the same branch. I can finesse it and remove the other bit though.

**Comment by ArchonMegalon** [comment]
@chummer5a Could you please do that for now please? The finesse thing. I still have to figure out how to handle github. I will use the "seperate branch" thing from now on, but I do have changed a lot in this already (but not yet commited), and don't want to risk anything...

**Comment by ArchonMegalon** [comment]
Is it on me to "close and comment" this request?

**Comment by chummer5a** [comment]
I'm going to have another crack at how the Tooltip is generated and stored, I'd prefer that we be able to show that the Limited and Extended drain reductions than just ignore that it's doing it.

**Pull request closed without merging**
